# The modifications of the output file from Kalibr:
# 1. For each matrix (e.g. cam0/T_cam_imu), remove the brackets and minus sign for each line. Use one pair of brackets for each matrix.
# 2. Add the T_imu_body at the end of the calibration file (usually set to identity).
cam0:
  T_cam_imu:
    [0.014865542981794,   0.999557249008346,  -0.025774436697440,   0.065222909535531,
    -0.999880929698575,   0.014967213324719,   0.003756188357967,  -0.020706385492719,
     0.004140296794224,   0.025715529947966,   0.999660727177902,  -0.008054602460030,
                     0,                   0,                   0,   1.000000000000000]
  camera_model: pinhole
  distortion_coeffs: [-0.28340811, 0.07395907, 0.00019359, 1.76187114e-05]
  distortion_model: radtan
  intrinsics: [458.654, 457.296, 367.215, 248.375]
  resolution: [752, 480]
  timeshift_cam_imu: 0.0
T_imu_body:
  [1.0000, 0.0000, 0.0000, 0.0000,
  0.0000, 1.0000, 0.0000, 0.0000,
  0.0000, 0.0000, 1.0000, 0.0000,
  0.0000, 0.0000, 0.0000, 1.0000]

